# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 您的博客名称
subtitle: '个人博客副标题'
description: '这里写您的博客描述'
keywords: 博客,技术,生活
author: 您的名字
language: zh-CN
timezone: 'Asia/Shanghai'

# URL
url: https://您的用户名.github.io

# Extensions
theme: next
